version: '3.1'

services:

    mysql8:
        build: ./mysql8
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./mysql8/data:/var/lib/mysql

    phpmyadmin:
        build: ./phpmyadmin
        restart: always
        links:
            - mysql8:db
        ports:
            - 8080:80
