version: '3.1'

services:

    mysql8:
        image: mysql:8
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root

    phpmyadmin:
        image: phpmyadmin
        restart: always
        links:
            - "mysql8:db"
        ports:
            - "8080:80"
